### ISSUE TITLE
Remove packages that provide their own typings

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#13364]
Moved here from Microsoft/types-publisher#215. We now automatically detect these, and there are a lot of them!

We should make pull requests for each of these and let both the package author and the typings author know that we will deprecate `@types/foo` in favor of `foo`.

- [ ] 3d-bin-packing (3d-bin-packing) as of 1.0.1 (our version: 0.0) (git+https://github.com/betterwaysystems/packer.git)
- [ ] ag-grid (ag-grid) as of 3.2.0 (our version: 2.1) (git+https://github.com/ceolter/ag-grid.git)
- [X] ajv (ajv) as of 4.0.0 (our version: 0.0) (git+https://github.com/epoberezkin/ajv.git) #13028
- [ ] angular-ui-router (Angular JS 1.1.5+ (ui.router module)) as of 1.0.0-alpha.1 (our version: 0.0) (git+https://github.com/angular-ui/ui-router.git)
- [ ] angular-ui-router-default (angular-ui-router-default 0.5+) as of 0.0.5 (our version: 0.0) (git+https://github.com/nonplus/- [ ]it)
- [ ] angular-ui-router-uib-modal (angular-ui-uib-modal 0.11+ (ui.router module)) as of 0.0.11 (our version: 0.0) (git+https://github.com/nonplus/- [ ].git)
- [ ] antd (Antd) as of 1.0.0-beta.4 (our version: 0.12) (git+https://github.com/ant-design/ant-design.git)
- [ ] anydb-sql (anydb-sql) as of 0.6.46 (our version: 0.0) (git://github.com/doxout/anydb-sql.git)
- [ ] apn (node-apn) as of 2.1.2 (our version: 0.0) (git+https://github.com/node-apn/node-apn.git)
- [ ] aws-sdk (aws-sdk) as of 2.7.0 (our version: 0.0) (git://github.com/aws/aws-sdk-js.git)
- [ ] axe-core (axe-core) as of 2.0.7 (our version: 2.0) (git+https://github.com/dequelabs/axe-core.git)
- [x] axios (axios) as of 0.14.0 (our version: 0.9) (git+https://github.com/mzabriskie/axios.git)
- [ ] azure-mobile-apps (azure-mobile-apps) as of 2.0.0-rc3 (our version: 2.1) (git+https://github.com/azure/azure-mobile-apps-node.git)
- [ ] babylonjs (BabylonJS) as of 2.4.1 (our version: 2.3) (git+https://github.com/BabylonJS/Babylon.js.git)
- [ ] base64url (base64url) as of 2.0.0-rc1 (our version: 2.0) (git://github.com/brianloveswords/base64url.git)
- [ ] bingmaps (Microsoft.Maps) as of 1.0.5 (our version: 7.0) (git+https://github.com/Microsoft/Bing-Maps-V8-TypeScript-Definitions.git)
- [ ] bowser (Bowser) as of 1.1.1 (our version: 1.0) (git+https://github.com/ded/bowser.git)
- [X] camel-case (camel-case) as of 1.2.1 (our version: 0.0) (git://github.com/blakeembrey/camel-case.git) #13323
- [X] change-case (change-case) as of 2.3.1 (our version: 0.0) (git+https://github.com/blakeembrey/change-case.git) #13323
- [ ] chunked-dc (chunked-dc) as of 0.2.2 (our version: 0.1) (git+https://github.com/saltyrtc/chunked-dc-js.git)
- [X] constant-case (constant-case) as of 1.1.2 (our version: 0.0) (git://github.com/blakeembrey/constant-case.git) #13323
- [ ] cordova.plugins.diagnostic (cordova.plugins.diagnostic) as of 3.3.0 (our version: 3.3) (git+https://github.com/dpa99c/cordova-diagnostic-plugin.git)
- [ ] date-fns (date-fns) as of 1.11.0 (our version: 2.5) (git+https://github.com/date-fns/date-fns.git)
- [ ] devextreme (DevExtreme) as of 16.2.1-16288 (our version: 16.1)
- [X] dot-case (dot-case) as of 1.1.2 (our version: 0.0) (git://github.com/blakeembrey/dot-case.git) #13323
- [X] dva (dva) as of 1.1.0 (our version: 1.0) (git+https://github.com/dvajs/dva.git) (#13379)
- [ ] easystarjs (EasyStar.js) as of 0.3.1 (our version: 0.1) (git://github.com/prettymuchbryce/easystarjs.git)
- [ ] ecmarkup (emarkup) as of 3.4.0 (our version: 3.3) (git+https://github.com/bterlson/ecmarkup.git)
- [ ] electron-builder (electron-builder) as of 2.8.0 (our version: 2.0) (git+https://github.com/electron-userland/electron-builder.git)
- [ ] email-validator (email-validator) as of 1.0.6 (our version: 1.0) (http://github.com/Sembiance/email-validator.git)
- [ ] es6-error (es6-error) as of 3.2.0 (our version: 4.0) (git+https://github.com/bjyoungblood/es6-error.git)
- [ ] es6-promise (es6-promise) as of 3.3.0 (our version: 0.0) (git://github.com/stefanpenner/es6-promise.git)
- [ ] eventemitter2 (EventEmitter2) as of 1.0.5 (our version: 2.2) (git://github.com/hij1nx/EventEmitter2.git)
- [ ] eventemitter3 (EventEmitter3) as of 2.0.2 (our version: 1.2) (git://github.com/primus/eventemitter3.git)
- [ ] express-formidable (express-formidable) as of 0.1.3 (our version: 1.0) (git+https://github.com/noraesae/express-formidable.git)
- [ ] express-serve-static-core (Express) as of 0.1.0 (our version: 4.0)
- [ ] extended-listbox (extended-listbox) as of 1.1.3 (our version: 1.1) (git+https://github.com/code-chris/extended-listbox.git)
- [ ] fast-simplex-noise (FastSimplexNoise) as of 3.0.0-pre.5 (our version: 2.1) (git+https://github.com/joshforisha/fast-simplex-noise-js.git)
- [ ] firebase (Firebase API) as of 3.2.1 (our version: 2.4) (https://firebase.google.com/)
- [ ] foundation-sites (Foundation Sites) as of 6.3.0-rc3 (our version: 6.1) (git+https://github.com/zurb/foundation-sites.git)
- [ ] graphene-pk11 (graphene-pk11) as of 2.0.0 (our version: 2.0) (git+https://github.com/PeculiarVentures/graphene.git)
- [ ] gulp-typescript (gulp-typescript) as of 2.13.0 (our version: 0.0) (git+https://github.com/ivogabe/gulp-typescript.git)
- [ ] gulp-tslint (gulp-tslint) as of 4.2.0 (our version: 3.6) (git+https://github.com/panuhorsmalahti/gulp-tslint.git)
- [ ] iconv-lite (iconv-lite) as of 0.4.14 (our version: 0.0) (git://github.com/ashtuchkin/iconv-lite.git)
- [X] immutable (Facebook's Immutable) as of 3.8.0 (our version: 3.8) (git://github.com/facebook/immutable-js.git) #13365
- [X] inversify (inversify 2.0.0-rc.12) as of 1.2.0 (our version: 0.0) (git+https://github.com/inversify/InversifyJS.git) #13648
- [X] inversify-binding-decorators (inversify 1.0.0-beta.5) as of 2.0.0 (our version: 0.0) (git+https://github.com/inversify/- [ ]s.git) #13648
- [X] inversify-express-utils (inversify-express-utils) as of 2.0.0 (our version: 1.0) (git+https://github.com/inversify/inversify-express-utils.git) #13648
- [X] inversify-inject-decorators (inversify-inject-decorators 1.0.0-beta.1) as of 2.0.0 (our version: 0.0) (git+https://github.com/inversify/- [ ].git) #13648
- [X] inversify-logger-middleware (inversify-logger-middleware) as of 2.0.0 (our version: 1.0) (git+https://github.com/inversify/- [ ].git) #13648
- [X] inversify-restify-utils (inversify-restify-utils) as of 2.0.0 (our version: 1.0) (git+https://github.com/inversify/inversify-restify-utils.git) #13648
- [X] is-lower-case (is-lower-case) as of 1.1.2 (our version: 0.0) (git://github.com/blakeembrey/is-lower-case.git) #13323
- [X] is-upper-case (is-upper-case) as of 1.1.2 (our version: 0.0) (git://github.com/blakeembrey/is-upper-case.git) #13323
- [ ] js-data (JSData) as of 3.0.0-beta.3 (our version: 2.8) (git+https://github.com/js-data/js-data.git)
- [ ] js-data-http (JSData Http Adapter) as of 3.0.0-beta.3 (our version: 1.2) (git+https://github.com/js-data/js-data-http.git)
- [ ] jsnlog (JSNLog v2.17.3+) as of 2.17.2 (our version: 0.0) (git+https://github.com/mperdeck/jsnlog.js.git)
- [ ] jsonschema (jsonschema) as of 1.1.1 (our version: 0.0) (git://github.com/tdegrunt/jsonschema.git)
- [ ] knockout-paging (knockout-paging) as of 0.3.1 (our version: 0.0) (git@github.com/ErikSchierboom/knockout-paging.git)
- [ ] knockout-pre-rendered (knockout-pre-rendered) as of 0.7.1 (our version: 0.0) (git+https://github.com/ErikSchierboom/knockout-pre-rendered.git)
- [ ] localforage-cordovasqlitedriver (localforage-cordovasqlitedriver module v1.0+) as of 1.5.0 (our version: 0.0) (git://github.com/thgreasi/- [ ]iver.git)
- [ ] log4javascript (log4javascript) as of 1.4.13-1 (our version: 1.4) (https://github.com/Ritzlgrmft/log4javascript.git)
- [X] lower-case (lower-case) as of 1.1.3 (our version: 0.0) (git://github.com/blakeembrey/lower-case.git) #13323
- [X] lower-case-first (lower-case-first) as of 1.0.1 (our version: 0.0) (git://github.com/blakeembrey/lower-case-first.git) #13323
- [ ] maquette (maquette) as of 2.1.6 (our version: 0.0) (git+https://github.com/AFASSoftware/maquette.git)
- [ ] mendixmodelsdk (mendixmodelsdk) as of 0.8.1 (our version: 0.0) (gitlab@gitlab.srv.hq.mendix.net:MetaServices/MetaServices.git)
- [ ] microgears (microgears) as of 4.0.5 (our version: 4.0) (git+https://github.com/marcusdb/microGears.git)
- [ ] mobile-detect (mobile-detect) as of 1.3.4 (our version: 1.2) (git+https://github.com/hgoebl/mobile-detect.js.git)
- [ ] mobservable (mobservable) as of 0.6.11 (our version: 0.6) (git+https://github.com/mweststrate/mobservable.git)
- [ ] mobservable-react (mobservable) as of 1.0.0-alpha.1 (our version: 0.1) (git+https://github.com/mweststrate/mobservable-react.git)
- [ ] node-mysql-wrapper (node-mysql-wrapper) as of 2.4.0 (our version: 0.0) (git+https://github.com/nodets/node-mysql-wrapper.git)
- [ ] numbro (Numbro.js) as of 1.8.0 (our version: 0.0) (git+https://github.com/foretagsplatsen/numbro.git)
- [ ] onsenui (Onsen UI) as of 2.0.0-rc.12 (our version: 0.0) (git+https://github.com/OnsenUI/OnsenUI.git)
- [X] param-case (param-case) as of 1.1.2 (our version: 0.0) (git://github.com/blakeembrey/param-case.git) #13323
- [ ] parse5 (parse5) as of 3.0.0 (our version: 2.2) (git://github.com/inikulin/parse5.git)
- [X] pascal-case (pascal-case) as of 1.1.2 (our version: 0.0) (git://github.com/blakeembrey/pascal-case.git) #13323
- [X] path-case (path-case) as of 1.1.2 (our version: 0.0) (git://github.com/blakeembrey/path-case.git) #13323
- [ ] path-to-regexp (path-to-regexp) as of 1.3.0 (our version: 1.0) (git+https://github.com/pillarjs/path-to-regexp.git)
- [ ] perfect-scrollbar (perfect-scrollbar) as of 0.6.13 (our version: 0.6) (git+https://github.com/noraesae/perfect-scrollbar.git)
- [ ] pg-promise (pg-promise) as of 5.4.3 (our version: 0.0) (git+https://github.com/vitaly-t/pg-promise.git)
- [ ] pkcs11js (pkcs11js) as of 1.0.4 (our version: 1.0) (git://github.com/PeculiarVentures/pkcs11js.git)
- [ ] plottable (Plottable) as of 2.0.1-beta.0 (our version: 1.4) (git+https://github.com/palantir/plottable.git)
- [ ] protobufjs (ProtoBuf.js) as of 6.0.0 (our version: 5.0) (git+https://github.com/dcodeIO/protobuf.js.git)
- [ ] qrcode-generator (grcode-generator) as of 1.0.6 (our version: 0.0) (git+https://github.com/kazuhikoarase/qrcode-generator.git)
- [ ] raven-js (Raven.js) as of 3.1.0 (our version: 0.0) (git://github.com/getsentry/raven-js.git)
- [ ] redux-bootstrap (react-bootstrap) as of 1.0.0 (our version: 1.0) (git+https://github.com/remojansen/redux-bootstrap.git)
- [ ] redux-mock-store (Redux Mock Store) as of 1.0.3 (our version: 0.0) (git+https://github.com/arnaudbenard/redux-mock-store.git)
- [ ] redux-saga (redux-saga) as of 0.10.5 (our version: 0.9) (git+https://github.com/yelouafi/redux-saga.git)
- [ ] reflect-metadata (reflect-metadata) as of 0.1.0 (our version: 0.0) (git+https://github.com/rbuckton/ReflectDecorators.git)
- [ ] reselect (reselect) as of 2.2.0 (our version: 2.0) (git+https://github.com/reactjs/reselect.git)
- [ ] rest-io (rest-io) as of 4.1.0 (our version: 4.0) (git+https://github.com/EnoF/rest-io.git)
- [ ] samchon-collection (Samchon Collection) as of 0.0.0-a (our version: 0.0) (git+https://github.com/samchon/framework.git)
- [ ] samchon-framework (Samchon Framework v2.0.0-gamma.9) as of 1.1.0 (our version: 0.0) (git+https://github.com/samchon/framework.git)
- [ ] samchon-library (Samchon Library) as of 0.0.0-a (our version: 0.0) (git+https://github.com/samchon/framework.git)
- [ ] scanf (node-scanf) as of 0.7.3 (our version: 0.0) (git+https://github.com/Lellansin/node-scanf.git)
- [ ] sendgrid (sendgrid) as of 4.3.0 (our version: 2.0) (git://github.com/sendgrid/sendgrid-nodejs.git)
- [X] sentence-case (sentence-case) as of 1.1.3 (our version: 0.0) (git://github.com/blakeembrey/sentence-case.git) #13323
- [X] snake-case (snake-case) as of 1.1.2 (our version: 0.0) (git://github.com/blakeembrey/snake-case.git) #13323
- [ ] ss-utils (ServiceStack Utils) as of 0.1.5 (our version: 0.0) (git+https://github.com/ServiceStack/ss-utils.git)
- [ ] sugar (Sugar) as of 2.0.2 (our version: 1.3) (git+https://github.com/andrewplummer/Sugar.git)
- [ ] survey-knockout (Survey JavaScript library) as of 0.10.0 (our version: 0.9) (git+https://github.com/andrewtelnov/surveyjs.git)
- [ ] svg-pan-zoom (svg-pan-zoom) as of 3.4.0 (our version: 3.3) (git+https://github.com/ariutta/svg-pan-zoom.git)
- [ ] svg.js (svg.js) as of 2.3.1 (our version: 0.0) (git+https://github.com/wout/svg.js.git)
- [X] swap-case (swap-case) as of 1.1.2 (our version: 0.0) (git://github.com/blakeembrey/swap-case.git) #13323
- [ ] tabris (Tabris.js) as of 1.8.0 (our version: 1.2) (git+https://github.com/eclipsesource/tabris-js.git)
- [ ] tcomb (tcomb) as of 2.6.0 (our version: 1.0) (git+https://github.com/gcanti/tcomb.git)
- [ ] timezonecomplete (timezonecomplete) as of 2.0.0-alpha.1 (our version: 1.15) (git+ssh://git@github.com/spiritit/timezonecomplete.git)
- [X] title-case (title-case) as of 1.1.2 (our version: 0.0) (git://github.com/blakeembrey/title-case.git) #13323
- [X] tsmonad (TsMonad) as of 0.5.0 (our version: 0.0) (git+https://github.com/cbowdon/TsMonad.git) #13378
- [ ] typescript-stl (TypeScript-STL) as of 0.9.3 (our version: 1.2) (git+https://github.com/samchon/typescript-stl.git)
- [X] upper-case (upper-case) as of 1.1.3 (our version: 0.0) (git://github.com/blakeembrey/upper-case.git) #13323
- [X] upper-case-first (upper-case-first) as of 1.1.2 (our version: 0.0) (git://github.com/blakeembrey/upper-case-first.git) #13323
- [ ] validate.js (Validate.js) as of 0.11.0 (our version: 0.0) (git+https://github.com/ansman/validate.js.git)
- [ ] vso-node-api (vso-node-api) as of 4.0.0 (our version: 0.3) (git+https://github.com/Microsoft/vso-node-api.git)
- [ ] vue-router (vue-router) as of 2.0.0-rc.6 (our version: 0.7)
- [X] vue (vuejs) as of 2.0.0-rc.5 (our version: 1.0) (git+https://github.com/vuejs/vue.git) #13236
- [ ] webcola (webcola) as of 3.2.0 (our version: 3.1) (git+https://github.com/tgdwyer/WebCola.git)
- [ ] x2js (x2js) as of 3.1.0 (our version: 0.0) (git+https://github.com/Axinom/x2js.git)
- [ ] zone.js (Zone.js) as of 0.5.12 (our version: 0.0) (git://github.com/angular/zone.js.git)

**Comment by peterennis** [comment]
I am looking into fixing the definitions package for svg.js
Ref: https://github.com/svgdotjs/svg.js/issues/597
Ref: https://github.com/Microsoft/dts-gen/issues/40
What is the recommended process to follow so that
we can keep definitions aligned with project releases?
dtsgen seems to have run into a wall.

**Comment by rbrundritt** [comment]
This is becoming a pain to keep in sync with the official definitions that are directly published by the Bing Maps team. Can we remove bing maps from DefinatelyTyped.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
