### ISSUE TITLE
[@types/jest] Missing test.todo method

### ISSUE THREAD

**Issue by lonix1** [DefinitelyTyped/DefinitelyTyped#32704]
- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @JoshuaKGoldberg @bradleyayers

`jest` =  24.0.0
`@types/jest` = 23.3.13

Missing [test.todo](https://jestjs.io/docs/en/api.html#testtodoname).

**Comment by wsmd** [comment]
Hi @lonix1! This is currently in the works https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32569
