### ISSUE TITLE
For Node.js 10.x and 12.x the import.meta object is incompletely defined

### ISSUE THREAD

**Issue by robogeek** [DefinitelyTyped/DefinitelyTyped#35222]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
 - Authors: @tdreyno @kamal @leemhenson @jonmagic @farcaller 

I have already asked the question part of this on Stack Overflow:  https://stackoverflow.com/questions/55998413/equivalent-for-dirname-in-typescript-when-using-target-module-esnext

The issue is that using TypeScript with @types/node etc installed, and I need to calculate the value for `__dirname`, the reference to `import.meta.url` cannot be compiled by the TypeScript compiler.

In the Node.js 12.x documentation it says to calculate `__dirname` from `import.meta.url`.

But referencing that variable in some TypeScript code causes the compilation to fail

```
tdn.ts:7:25 - error TS2339: Property 'url' does not exist on type 'ImportMeta'.

7 console.log(import.meta.url);
```

I found in `node_modules//typescript/lib/lib.es5.d.ts` this code:

```
/**
 * The type of `import.meta`.
 *
 * If you need to declare that a given property exists on `import.meta`,
 * this type may be augmented via interface merging.
 */
interface ImportMeta {
}
```

So.... 

Clearly the `ImportMeta` interface is not properly defined.  For Node.js there is a `url` field that is clearly defined in the Node.js documentation.

The definition in the TypeScript source probably should not change.  But the definition in `@types/node` should probably change to match reality.

**Comment by SimonSchick** [comment]
I guess this is a super niche use case, `mjs` isn't really used that much yet (and probably won't be in the coming years).

I will look into adding it.
