### ISSUE TITLE
[@types/tryghost__content-api] meta PostsOrPages's property considered undefined

### ISSUE THREAD

**Issue by Gwenael22** [DefinitelyTyped/DefinitelyTyped#44487]
Hello,

When i am trying to access to the meta property of PostsOrPages object `posts.meta`, i have an execution error "TypeError: posts.meta is undefined" but i have no typescript compilation error (when i had a test in my code to check if property is set, it consider that the property is undefined).
If i only use the content of the Array<T> property, everything is working fine. 

I have added a console.log to debug and meta property contains values : 
`{
  pagination: { page: 1, limit: 3, pages: 2, total: 4, next: 2, prev: null }
}
`

I am using : 
- typescript 3.8.3
- @types/tryghost__content-api 1.3.3
- @tryghost/content-api 1.4.1
- next : 9.3.6
- react : 16.13.1

Thks for your help

- [X] I tried using the `@types/tryghost__content-api` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @knguyen0125 , @antonve, @maveric1977, @thrymgjol

**Comment by Gwenael22** [comment]
After more investiguation, my problem to a JSON serialization / deserialization on PostsOrPages object when i use Next.js method getServerSideProps.
The workaround is to use Pagination object independantly from PostsOrPages object for JSON serialization.
